from __future__ import annotations

from dataclasses import dataclass
from math import hypot
from typing import Iterable, List, Sequence, Tuple

Point = Tuple[float, float]
Path2D = List[Point]


@dataclass
class GCodeConfig:
    draw_feed_mm_min: int = 1200
    travel_feed_mm_min: int = 3000
    pen_up_cmd: str = "M5"
    pen_down_cmd: str = "M3 S30"
    use_absolute_positioning: bool = True
    return_home: bool = True
    include_header: bool = True
    include_footer: bool = True
    precision: int = 3


def _dist(a: Point, b: Point) -> float:
    return hypot(a[0] - b[0], a[1] - b[1])


def optimize_paths(paths: Sequence[Path2D], start: Point = (0.0, 0.0)) -> List[Path2D]:
    remaining = [path for path in paths if len(path) >= 2]
    if not remaining:
        return []

    optimized: List[Path2D] = []
    cursor = start

    while remaining:
        best_idx = 0
        best_reverse = False
        best_distance = float("inf")

        for idx, path in enumerate(remaining):
            d_start = _dist(cursor, path[0])
            d_end = _dist(cursor, path[-1])

            if d_start < best_distance:
                best_distance = d_start
                best_idx = idx
                best_reverse = False

            if d_end < best_distance:
                best_distance = d_end
                best_idx = idx
                best_reverse = True

        selected = remaining.pop(best_idx)
        if best_reverse:
            selected = list(reversed(selected))

        optimized.append(selected)
        cursor = selected[-1]

    return optimized


def _fmt(value: float, precision: int) -> str:
    return f"{value:.{precision}f}".rstrip("0").rstrip(".")


def _line(x: float, y: float, cmd: str, feed: int | None, precision: int) -> str:
    feed_str = f" F{feed}" if feed is not None else ""
    return f"{cmd} X{_fmt(x, precision)} Y{_fmt(y, precision)}{feed_str}"


def generate_gcode(paths: Iterable[Path2D], config: GCodeConfig | None = None) -> List[str]:
    cfg = config or GCodeConfig()
    lines: List[str] = []

    if cfg.include_header:
        lines.extend(
            [
                "; Generated by CNCPlotter python pipeline",
                "G21",  # Units in millimeters.
                "G90" if cfg.use_absolute_positioning else "G91",
                cfg.pen_up_cmd,
            ]
        )

    for path in paths:
        if len(path) < 2:
            continue

        x0, y0 = path[0]
        lines.append(_line(x0, y0, "G0", cfg.travel_feed_mm_min, cfg.precision))
        lines.append(cfg.pen_down_cmd)

        for x, y in path[1:]:
            lines.append(_line(x, y, "G1", cfg.draw_feed_mm_min, cfg.precision))

        lines.append(cfg.pen_up_cmd)

    if cfg.return_home:
        lines.append(_line(0.0, 0.0, "G0", cfg.travel_feed_mm_min, cfg.precision))

    if cfg.include_footer:
        lines.extend(["M2", ";"])

    return lines


def save_gcode(lines: Sequence[str], output_path: str) -> None:
    with open(output_path, "w", encoding="utf-8") as handle:
        for line in lines:
            handle.write(line.rstrip() + "\n")